package io.codelaser.maddi.run.openjdkmain;

import ch.qos.logback.classic.Level;
import org.apache.commons.cli.ParseException;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Tag;

/**
 * ActiveMQ broker (concurrency-heavy corpus: destinations, cursors, thread pools; qualified inner-class
 * creations). Green since 2026-07-18 (certified fixpoint, ~2min at PARALLEL defaults). Config generated by
 * the maddi Maven plugin; the corpus-root copy carries an absolute workingDirectory.
 */
@Tag("slow")
public class TestActiveMQBroker {

    @BeforeAll
    public static void beforeAll() {
        ((ch.qos.logback.classic.Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME)).setLevel(Level.INFO);
        ((ch.qos.logback.classic.Logger) LoggerFactory.getLogger("io.codelaser.maddi.shallow")).setLevel(Level.DEBUG);
        ((ch.qos.logback.classic.Logger) LoggerFactory
                .getLogger("io.codelaser.maddi.modification.link.impl.linkgraph.RedundantLinks")).setLevel(Level.ERROR);
    }

    private static final Path CONFIG = TestOssCorpus.config("activemq");

    @Test
    public void test() throws IOException, ParseException {
        Assumptions.assumeTrue(Files.exists(CONFIG),
                "requires the activemq corpus checkout with its generated input configuration");
        int exitValue = Main.execute(new String[]{
                "--input-configuration=" + CONFIG
                , "--analysis-steps=modification"
                , "--preload-analysis-results-dirs=../maddi-aapi-archive/src/main/resources/io/codelaser/maddi/aapi/archive/analyzedPackageFiles/jdk"
        });
        assertEquals(Main.EXIT_OK, exitValue);
    }
}
